Attempt to set the core file size during configure. If successful then we set the limit to unlimited when the ircd is started

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11410,7 +11410,8 @@ done
 
 
 
-for ac_func in alarm dup2 getpass gettimeofday memmove memset regcomp select socket strcasecmp strchr strdup strerror strncasecmp strpbrk strrchr strstr strtol strtoul kqueue setrlimit getrusage times
+
+for ac_func in alarm dup2 getpass gettimeofday memmove memset regcomp select socket strcasecmp strchr strdup strerror strncasecmp strpbrk strrchr strstr strtol strtoul strspn kqueue setrlimit getrusage times
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -11914,6 +11915,83 @@ fi
 done
 test -n "$BASH" || BASH="/bin/bash"
 
+
+{ echo "$as_me:$LINENO: checking if we can set the core size to unlimited" >&5
+echo $ECHO_N "checking if we can set the core size to unlimited... $ECHO_C" >&6; }
+if test "${ac_cv_force_core+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/time.h>
+#include <sys/resource.h>
+#include <unistd.h>
+int main() {
+struct rlimit corelim;
+corelim.rlim_cur = corelim.rlim_max = RLIM_INFINITY;
+if (setrlimit(RLIMIT_CORE, &corelim))
+exit(1);
+exit(0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_force_core=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ac_cv_force_core=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_force_core" >&5
+echo "${ECHO_T}$ac_cv_force_core" >&6; }
+if test "$ac_cv_force_core" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define FORCE_CORE
+_ACEOF
+
+fi
 
 for ac_prog in flex lex
 do
