Added checkregex from unreal to check for dodgy regex's.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11317,6 +11317,61 @@ then
     CFLAGS="-fno-strict-aliasing $CFLAGS"
 fi
 
+{ echo "$as_me:$LINENO: checking whether $CC accepts -funsigned-char" >&5
+echo $ECHO_N "checking whether $CC accepts -funsigned-char... $ECHO_C" >&6; }
+ac_save_cc="$CC"
+CC="$CC -funsigned-char"
+if test "$cross_compiling" = yes; then
+  ac_cv_unsigned_char_ok=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int main() { return 0; }
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_unsigned_char_ok=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ac_cv_unsigned_char_ok=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+CC="$ac_save_cc"
+{ echo "$as_me:$LINENO: result: $ac_cv_unsigned_char_ok" >&5
+echo "${ECHO_T}$ac_cv_unsigned_char_ok" >&6; }
+if test $ac_cv_unsigned_char_ok = yes
+then
+    CFLAGS="-funsigned-char $CFLAGS"
+fi
 
 if test x"$unet_cv_enable_warnings" = xyes; then
     CFLAGS="-Wall $CFLAGS"
