Refer to the changelog, bringing BoxenIRCu code over.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -861,8 +861,8 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-openssl-includes Specify location of OpenSSL header files
-  --with-openssl-libs Specify location of OpenSSL libs
+  --with-openssl-includes Specify location of OpenSSL header files (default /usr/include)
+  --with-openssl-libs     Specify location of OpenSSL libs (default /usr/lib)
   --with-symlink=name     Name to give the symlink; if name is "no," no
                           symlink will be created.
   --with-mode=mode        Permissions (in octal) to give the binary
@@ -876,6 +876,7 @@ Optional Packages:
   --with-cpath=file       Set server configuration file
   --with-lpath=file       Set the debugging log file
   --with-maxcon=maxcon    Maximum number of connections server will accept
+  --without-sense-of-humor   Specify this if you have no sense of humor
 
 Some influential environment variables:
   CC          C compiler command
@@ -944,7 +945,7 @@ ac_abs_top_srcdir=`cd "$ac_dir" && cd $ac_top_srcdir && pwd`
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd "$ac_popdir"
+    cd $ac_popdir
   done
 fi
 
@@ -1141,7 +1142,7 @@ _ASBOX
       echo "$as_me: caught signal $ac_signal"
     echo "$as_me: exit $exit_status"
   } >&5
-  rm -f core *.core &&
+  rm -f core core.* *.core &&
   rm -rf conftest* confdefs* conf$$* $ac_clean_files &&
     exit $exit_status
      ' 0
@@ -2163,7 +2164,8 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   for ac_declaration in \
-   '' \
+   ''\
+   '#include <stdlib.h>' \
    'extern "C" void std::exit (int) throw (); using std::exit;' \
    'extern "C" void std::exit (int); using std::exit;' \
    'extern "C" void exit (int) throw ();' \
@@ -2177,8 +2179,8 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_declaration
 #include <stdlib.h>
+$ac_declaration
 int
 main ()
 {
@@ -3567,7 +3569,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 ac_cv_header_stdc=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 fi
@@ -3642,7 +3644,6 @@ _ACEOF
 fi
 
 done
-
 
 
 
@@ -3972,7 +3973,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 ac_cv_c_bigendian=yes
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
@@ -4548,7 +4549,7 @@ echo "$as_me: error: cannot compute sizeof (short), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -4909,7 +4910,7 @@ echo "$as_me: error: cannot compute sizeof (int), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -5270,7 +5271,7 @@ echo "$as_me: error: cannot compute sizeof (long), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -5631,7 +5632,7 @@ echo "$as_me: error: cannot compute sizeof (void *), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -6606,7 +6607,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 ac_cv_sys_restartable_syscalls=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 echo "$as_me:$LINENO: result: $ac_cv_sys_restartable_syscalls" >&5
@@ -6936,7 +6937,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 unet_cv_sys_nonblocking_posix=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 echo "$as_me:$LINENO: result: $unet_cv_sys_nonblocking_posix" >&5
@@ -7010,7 +7011,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 unet_cv_sys_nonblocking_bsd=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 echo "$as_me:$LINENO: result: $unet_cv_sys_nonblocking_bsd" >&5
@@ -7132,7 +7133,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 unet_cv_sys_signal_bsd=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 echo "$as_me:$LINENO: result: $unet_cv_sys_signal_bsd" >&5
@@ -7465,6 +7466,7 @@ _ACEOF
 
 fi
 
+
 echo "$as_me:$LINENO: checking whether to enable OpenSSL support" >&5
 echo $ECHO_N "checking whether to enable OpenSSL support... $ECHO_C" >&6
 # Check whether --enable-ssl or --disable-ssl was given.
@@ -7483,40 +7485,50 @@ echo "$as_me:$LINENO: result: $unet_cv_enable_ssl" >&5
 echo "${ECHO_T}$unet_cv_enable_ssl" >&6
 
 
-echo "$as_me:$LINENO: checking looking for OpenSSL includes" >&5
-echo $ECHO_N "checking looking for OpenSSL includes... $ECHO_C" >&6
+if test x"$unet_cv_enable_ssl" = xyes; then
+  echo "$as_me:$LINENO: checking for OpenSSL includes" >&5
+echo $ECHO_N "checking for OpenSSL includes... $ECHO_C" >&6
 
 # Check whether --with-openssl-includes or --without-openssl-includes was given.
 if test "${with_openssl_includes+set}" = set; then
   withval="$with_openssl_includes"
-  unet_cv_with_openssl_inc_prefix=-I$with_sslinc_val
+  base_ssl_inc=$withval
+else
+  base_ssl_inc=/usr/include
 fi;
-echo "$as_me:$LINENO: result: $unet_cv_with_openssl_inc_prefix" >&5
+  unet_cv_with_openssl_inc_prefix=$base_ssl_inc
+  echo "$as_me:$LINENO: result: $unet_cv_with_openssl_inc_prefix" >&5
 echo "${ECHO_T}$unet_cv_with_openssl_inc_prefix" >&6
 
-echo "$as_me:$LINENO: checking looking for OpenSSL libraries" >&5
-echo $ECHO_N "checking looking for OpenSSL libraries... $ECHO_C" >&6
+cat >>confdefs.h <<_ACEOF
+#define SSL_INCLUDES_PATH "$base_ssl_inc"
+_ACEOF
+
+
+  echo "$as_me:$LINENO: checking for OpenSSL libraries" >&5
+echo $ECHO_N "checking for OpenSSL libraries... $ECHO_C" >&6
 
 # Check whether --with-openssl-libs or --without-openssl-libs was given.
 if test "${with_openssl_libs+set}" = set; then
   withval="$with_openssl_libs"
-  unet_cv_with_openssl_prefix=$with_ssllib_val
+  unet_cv_with_openssl_prefix=$withval
 else
   unet_cv_with_openssl_prefix=/usr/lib
 fi;
-echo "$as_me:$LINENO: result: $unet_cv_with_openssl_prefix" >&5
+  echo "$as_me:$LINENO: result: $unet_cv_with_openssl_prefix" >&5
 echo "${ECHO_T}$unet_cv_with_openssl_prefix" >&6
 
-if test "x$unet_cv_enable_ssl" = xyes; then
-	###
-	### Check for OpenSSL
-	###
-	save_CFLAGS=$CFLAGS;
-	CFLAGS="-lcrypto";
+cat >>confdefs.h <<_ACEOF
+#define SSL_LIBS_PATH "$unet_cv_with_openssl_prefix"
+_ACEOF
 
-	unet_cv_enable_ssl="no";
-	OPENSSL_LDFLAGS="";
-	echo "$as_me:$LINENO: checking for SSL_read in -lssl" >&5
+
+  save_CFLAGS=$CFLAGS;
+  CFLAGS="-lcrypto";
+
+  unet_cv_enable_ssl="no";
+  OPENSSL_LDFLAGS="";
+  echo "$as_me:$LINENO: checking for SSL_read in -lssl" >&5
 echo $ECHO_N "checking for SSL_read in -lssl... $ECHO_C" >&6
 if test "${ac_cv_lib_ssl_SSL_read+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -7572,7 +7584,7 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_ssl_SSL_read" >&5
 echo "${ECHO_T}$ac_cv_lib_ssl_SSL_read" >&6
 if test $ac_cv_lib_ssl_SSL_read = yes; then
 
-	  echo "$as_me:$LINENO: checking for X509_new in -lcrypto" >&5
+    echo "$as_me:$LINENO: checking for X509_new in -lcrypto" >&5
 echo $ECHO_N "checking for X509_new in -lcrypto... $ECHO_C" >&6
 if test "${ac_cv_lib_crypto_X509_new+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -7630,7 +7642,7 @@ if test $ac_cv_lib_crypto_X509_new = yes; then
 
 
 
-for ac_header in openssl/ssl.h openssl/err.h
+for ac_header in $base_ssl_inc/openssl/ssl.h $base_ssl_inc/openssl/err.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -7767,9 +7779,9 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
-	      unet_cv_enable_ssl="yes";
-	      OPENSSL_LDFLAGS="-lssl -lcrypto"
-              SSL_C=ssl.c
+        unet_cv_enable_ssl="yes";
+        OPENSSL_LDFLAGS="-lssl -lcrypto -lssl"
+        SSL_C=ssl.c
 
 
 fi
@@ -7782,20 +7794,18 @@ fi
 
 fi
 
-	CFLAGS=$save_CFLAGS
+  CFLAGS=$save_CFLAGS
 
-	if test "x$unet_cv_enable_ssl" = xyes; then
+  if test "x$unet_cv_enable_ssl" = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_SSL
 _ACEOF
 
 
-		LIBS="$LIBS -L$unet_cv_with_openssl_prefix $OPENSSL_LDFLAGS"
-		CFLAGS="$CFLAGS $openssl_inc_prefix"
-	fi
-else
-	unet_cv_enable_ssl="no"
+    LIBS="$LIBS -L$unet_cv_with_openssl_prefix $OPENSSL_LDFLAGS"
+    CFLAGS="$CFLAGS -I$unet_cv_with_openssl_inc_prefix"
+  fi
 fi
 
 
@@ -7865,6 +7875,66 @@ _ACEOF
     ENGINE_C="engine_kqueue.c $ENGINE_C"
 fi
 
+echo "$as_me:$LINENO: checking for epoll_create in -lepoll" >&5
+echo $ECHO_N "checking for epoll_create in -lepoll... $ECHO_C" >&6
+if test "${ac_cv_lib_epoll_epoll_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lepoll  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char epoll_create ();
+int
+main ()
+{
+epoll_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_epoll_epoll_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_epoll_epoll_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_epoll_epoll_create" >&5
+echo "${ECHO_T}$ac_cv_lib_epoll_epoll_create" >&6
+if test $ac_cv_lib_epoll_epoll_create = yes; then
+  have_epoll_lib=yes
+else
+  have_epoll_lib=no
+fi
+
 echo "$as_me:$LINENO: checking whether to enable the epoll event engine" >&5
 echo $ECHO_N "checking whether to enable the epoll event engine... $ECHO_C" >&6
 # Check whether --enable-epoll or --disable-epoll was given.
@@ -7880,7 +7950,7 @@ fi
 
 fi;
 
-if test x"$ac_cv_header_sys_epoll_h" = xno -o x"$ac_cv_func_epoll" = xno; then
+if test x"$ac_cv_header_sys_epoll_h" = xno -o x"$ac_cv_func_epoll" = xno -o x"$have_epoll_lib" = xno; then
     unet_cv_enable_epoll=no
 fi
 
@@ -8298,6 +8368,229 @@ echo "${ECHO_T}$unet_cv_with_maxcon" >&6
 cat >>confdefs.h <<_ACEOF
 #define MAXCONNECTIONS $unet_cv_with_maxcon
 _ACEOF
+
+
+
+# Check whether --with-sense-of-humor or --without-sense-of-humor was given.
+if test "${with_sense_of_humor+set}" = set; then
+  withval="$with_sense_of_humor"
+
+            if test "$withval" = "no"; then
+              HUMOR=none
+            fi
+
+fi;
+
+
+if test -z "$HUMOR"; then
+
+echo "$as_me:$LINENO: checking for mass_quantities_of_beer in -lFridge" >&5
+echo $ECHO_N "checking for mass_quantities_of_beer in -lFridge... $ECHO_C" >&6
+if test "${ac_cv_lib_Fridge_mass_quantities_of_beer+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lFridge  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char mass_quantities_of_beer ();
+int
+main ()
+{
+mass_quantities_of_beer ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Fridge_mass_quantities_of_beer=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Fridge_mass_quantities_of_beer=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Fridge_mass_quantities_of_beer" >&5
+echo "${ECHO_T}$ac_cv_lib_Fridge_mass_quantities_of_beer" >&6
+if test $ac_cv_lib_Fridge_mass_quantities_of_beer = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBFRIDGE 1
+_ACEOF
+
+  LIBS="-lFridge $LIBS"
+
+fi
+
+
+echo "$as_me:$LINENO: checking for mass_quantities_of_any_alcohol in -lFridge" >&5
+echo $ECHO_N "checking for mass_quantities_of_any_alcohol in -lFridge... $ECHO_C" >&6
+if test "${ac_cv_lib_Fridge_mass_quantities_of_any_alcohol+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lFridge  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char mass_quantities_of_any_alcohol ();
+int
+main ()
+{
+mass_quantities_of_any_alcohol ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Fridge_mass_quantities_of_any_alcohol=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Fridge_mass_quantities_of_any_alcohol=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Fridge_mass_quantities_of_any_alcohol" >&5
+echo "${ECHO_T}$ac_cv_lib_Fridge_mass_quantities_of_any_alcohol" >&6
+if test $ac_cv_lib_Fridge_mass_quantities_of_any_alcohol = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBFRIDGE 1
+_ACEOF
+
+  LIBS="-lFridge $LIBS"
+
+else
+
+    echo "Warning: No alcohol was found in your refrigerator."
+    echo "  We highly suggest that you rectify this situation immediately."
+
+fi
+
+
+
+echo "$as_me:$LINENO: checking for life_signs in -lKenny" >&5
+echo $ECHO_N "checking for life_signs in -lKenny... $ECHO_C" >&6
+if test "${ac_cv_lib_Kenny_life_signs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lKenny  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char life_signs ();
+int
+main ()
+{
+life_signs ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Kenny_life_signs=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Kenny_life_signs=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Kenny_life_signs" >&5
+echo "${ECHO_T}$ac_cv_lib_Kenny_life_signs" >&6
+if test $ac_cv_lib_Kenny_life_signs = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBKENNY 1
+_ACEOF
+
+  LIBS="-lKenny $LIBS"
+
+else
+
+    echo "  Oh my god, they killed Kenny!  You bastards!"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_HUMOR 1
+_ACEOF
+
+
+fi
+
+fi
 
 
                               ac_config_files="$ac_config_files Makefile ircd/Makefile doc/Makefile"
