Ported 64bit compile problem fix (res_mkquery) from stable branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3924,6 +3924,7 @@ fi
 
 
 
+
 echo "$as_me:$LINENO: checking for library containing res_mkquery" >&5
 echo $ECHO_N "checking for library containing res_mkquery... $ECHO_C" >&6
 if test "${ac_cv_search_res_mkquery+set}" = set; then
@@ -4047,10 +4048,143 @@ if test "$ac_cv_search_res_mkquery" != no; then
   test "$ac_cv_search_res_mkquery" = "none required" || LIBS="$ac_cv_search_res_mkquery $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Unable to find library containing res_mkquery()" >&5
-echo "$as_me: error: Unable to find library containing res_mkquery()" >&2;}
-   { (exit 1); exit 1; }; }
+   echo "$as_me:$LINENO: checking for library containing __res_mkquery" >&5
+echo $ECHO_N "checking for library containing __res_mkquery... $ECHO_C" >&6
+if test "${ac_cv_search___res_mkquery+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search___res_mkquery=no
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __res_mkquery ();
+int
+main ()
+{
+__res_mkquery ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search___res_mkquery="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
 fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search___res_mkquery" = no; then
+  for ac_lib in resolv; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __res_mkquery ();
+int
+main ()
+{
+__res_mkquery ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search___res_mkquery="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search___res_mkquery" >&5
+echo "${ECHO_T}$ac_cv_search___res_mkquery" >&6
+if test "$ac_cv_search___res_mkquery" != no; then
+  test "$ac_cv_search___res_mkquery" = "none required" || LIBS="$ac_cv_search___res_mkquery $LIBS"
+
+cat >>confdefs.h <<_ACEOF
+#define RES_PREFIX "TRUE"
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: Unable to find library containing res_mkquery() or __res_mkquery(). Please install resolv library. (comes with libc6)" >&5
+echo "$as_me: error: Unable to find library containing res_mkquery() or __res_mkquery(). Please install resolv library. (comes with libc6)" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+
+
+fi
+
 
 
 ac_ext=c
@@ -10977,8 +11111,8 @@ _ACEOF
     LIBS="$LIBS -L$unet_cv_with_openssl_prefix $OPENSSL_LDFLAGS"
     CFLAGS="$CFLAGS -I$unet_cv_with_openssl_inc_prefix -I$unet_cv_with_kerberos_prefix"
   else
-    { { echo "$as_me:$LINENO: error: Unable to find OpenSSL, Use --with-openssl-includes and --with-openssl-libs if you have it installed in a different location" >&5
-echo "$as_me: error: Unable to find OpenSSL, Use --with-openssl-includes and --with-openssl-libs if you have it installed in a different location" >&2;}
+    { { echo "$as_me:$LINENO: error: Unable to find OpenSSL, Maybe you need to install the openssl and libssl-dev package, or use --with-openssl-includes and --with-openssl-libs if you have openssl installed in an odd location" >&5
+echo "$as_me: error: Unable to find OpenSSL, Maybe you need to install the openssl and libssl-dev package, or use --with-openssl-includes and --with-openssl-libs if you have openssl installed in an odd location" >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
